/* 在src/main/java路径下使用cmd执行命令：javah com.example.myapplication.MainActivity */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication_MainActivity */

#ifndef _Included_com_example_myapplication_MainActivity
#define _Included_com_example_myapplication_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplication_MainActivity
 * Method:    convertmp3
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_myapplication_MainActivity_convertmp3
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_myapplication_MainActivity
 * Method:    getLameVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myapplication_MainActivity_getLameVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
